# Migration `20200211102909-add_user_model`

This migration has been generated by vincent raveneau at 2/11/2020, 10:29:09 AM.
You can check out the [state of the schema](./schema.prisma) after the migration.

## Database Steps

```sql
CREATE TABLE "public"."User" (
    "id" text  NOT NULL ,
    PRIMARY KEY ("id")
) 
```

## Changes

```diff
diff --git schema.prisma schema.prisma
migration ..20200211102909-add_user_model
--- datamodel.dml
+++ datamodel.dml
@@ -1,0 +1,12 @@
+datasource db {
+  provider = "postgresql"
+    url      = "postgresql://postgres:postgres@localhost:5432/postgres?schema=public"
+    }
+
+generator client {
+  provider = "prisma-client-js"
+  }
+
+model User {
+  id String @id @default(cuid())
+  }
```


